sudo: required

env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

services:
  - docker

notifications:
  email: false

language: C++

before_install:
- ./scripts/dr.sh "./scripts/check_indentation.sh"

script:
- ./scripts/dr.sh "test -d build-travis && rm -rf build-travis; mkdir build-travis; cd build-travis; cmake -GNinja ../ -DBEM_ENABLE_TESTING=ON; ninja"
- ./scripts/dr.sh "cd build-travis; ctest -N; ctest -V"
